name: Java

on:
  push:
    paths:
      - '**.java'
      - '**.groovy'
  pull_request:
    paths:
      - '**.java'
      - '**.groovy'
    branches:
      - master

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
          cache: gradle
      - name: Compile project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
        env:
          ENV: DEV
          TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
          cache: gradle
      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
        env:
          ENV: DEV
          TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
