name: Style check
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - master

jobs:
  style:
    name: Google
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Code style
        uses: nikitasavinov/checkstyle-action@0.5.1
        with:
          level: error
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-review'
          tool_name: 'Code Style'