name: Code coverage

on:
  push:
    paths:
      - '**.java'
      - '**.groovy'
  pull_request:
    paths:
      - '**.java'
      - '**.groovy'
    branches:
      - master
    types:
      - 'opened'
      - 'reopened'

jobs:
  coverage:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v2