name: Check formatting

on:
  push:
    branches:
      - master
    paths:
      - "**/*.java"
  pull_request:
    paths:
      - "**/*.java"
  workflow_dispatch:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - uses: axel-op/googlejavaformat-action@v3
        with:
          skipCommit: true
          args: "--set-exit-if-changed"
