name: Spell checking
on:
  pull_request:
    types: [opened, reopened]
    paths: ["*.md", "*.markdown", "*.txt"]
  workflow_dispatch:

jobs:
  spelling:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: igsekor/pyspelling-any@v0.0.2
        name: Spellcheck