name: Test project

on:
  push:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
          cache: gradle
      - run: ./gradlew test -PexcludeTests
